services:
  samba:
    image: uttevgen/samba
    container_name: samba
    environment:
      USER: "samba"
      PASS: "secret"
    ports:
      - 445:445
    volumes:
      - /srv/storage:/storage
      - /srv/samba/smb.conf:/etc/samba/smb.conf
